---
- name: Update definitions and show health
  hosts: all
  tasks:
    - name: Update MD ATP definitions and check health
      shell: |
        set -e
        mdatp definitions update
        mdatp health
      args:
        executable: /bin/bash
      register: mdatp_health_output
      changed_when: "'Definitions successfully updated' in mdatp_health_output.stdout"

    - name: Display health check output
      debug:
        var: mdatp_health_output.stdout_lines
