---
- name: update definitions and show health
  hosts: all
  tasks:
    - name: Update MD ATP definitions
      shell: mdatp definitions update
    - name: mdatp healt check to output
      shell: mdatp health
      
