---
- name: update definitions
  hosts: vmadcappmycus01
  tasks:
    - name: Update MD ATP definitions
      shell: mdatp definitions update
    - name: Perform quick scan
      shell: mdatp scan quick
      
